name: Update Lists

on:
  push:
    paths:
      - "**.py"
      - "**.sh"
      - "**.yml"
      - "**.toml"
  workflow_dispatch:
  schedule:
    - cron: '35 19 * * *'

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true
          cache: "pip"

      - name: Check Python3 Version
        run: python3 --version

      - name: date
        run: date

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Generating IP Lists
        run: python3 ./src/list_generator.py

      - name: Generating CIDR Lists
        run: python3 ./src/generate_cidr.py

      - name: Commit changes
        run: |
          git config --local user.email '2001622+unalt@users.noreply.github.com'
          git config --local user.name 'unalt'
          git add lists/ README.md
          git commit -m 'Updated Lists [Automated]'
          git pull
          git push

      - name: Check diff
        run: git diff HEAD~1..HEAD
